# Source bash_aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Source local-only bashrc_local
if [ -f ~/.bashrc_local ]; then
    . ~/.bashrc_local
fi

# Set the default permissions for new files
umask 0002

# Initialize virtualenvwrapper
export WORKON_HOME=~/Virtualenvs
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'

# Ignore duplicates and lines that start with space in command history
export HISTCONTROL=ignoreboth
# Increase history size to 10,000 lines
export HISTSIZE=5000
export HISTFILESIZE=10000
# Don't save ls, bg, fg, history, and clear commands in the history
export HISTCONTROL='ls:bg:fg:history:clear'
# Add timestamps to the history
export HISTTIMEFORMAT='%y-%m-%d %T '

# Set the terminal colors for rxvt (change if terminal is different)
export TERM=rxvt

# Set the editor environment variable
export EDITOR=nvim

# Enable the globstar recursive match feature of the shell
shopt -s globstar

# Create commands mark, marks, and unmark that act like vim marks for directories
export MARKPATH=$HOME/.marks
function jump { 
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark { 
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark { 
    rm -i "$MARKPATH/$1"
}
function marks {
    ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
