# Bash aliases for use on new linux systems

alias aliases='vim ~/.bash_aliases'
alias ls='ls --color'
alias la='ls -Al'
alias ll='ls -l'
alias rm='rm -I --preserve-root -d -v'
alias venv='virtualenvwrapper'
alias venvstart='export WORKON_HOME=~/Virtualenvs ; source /usr/local/bin/virtualenvwrapper.sh'
alias lsvenv='lsvirtualenv'
alias cdvenv='cdvirtualenv'
alias mkvenv='mkvirtualenv'
alias rmvenv='rmvirtualenv'
alias ack='ack-grep'
